### ISSUE TITLE
Bug in Country Text Description

### ISSUE THREAD

**Issue by drosne** [drosne/LDH#33]
As you can see in this screenshot you'll understand that some text is not clean in the country text description. Is it possible to fix this in order to have something clean. It appears that there are no major problem in the front part but it's not clean to have such a difference in admin display 

![capture d ecran 2015-02-20 a 09 28 08](https://cloud.githubusercontent.com/assets/10349847/6285020/662d75b0-b8f7-11e4-9309-076f96861682.png)

It is supposed to be like this : 
![capture d ecran 2015-02-20 a 11 56 17](https://cloud.githubusercontent.com/assets/10349847/6285033/82ee2550-b8f7-11e4-90f4-def64306daf2.png)

I don't know where it is different but may be you can find it smartly ?

**Comment by krasizlatev** [comment]
Fixed.

**Comment by drosne** [comment]
good thanks
